### ISSUE TITLE
ACTIVIDAD 4_MAPA MENTAL

### ISSUE THREAD

**Issue by Jaczibeth** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Jaczibeth#1]
Mapa mental_Comunicacion oral y escrita
Jaczibeth Cruz Ramirez 1BS
![MAPAMENTAL_COMUNICACION ORALYESCRITA_JACZIBETH](https://user-images.githubusercontent.com/112178026/191203139-19c0c63b-65ae-434f-97b4-38afc8380ada.png)

[MAPAMENTAL_COMUNICACION ORALYESCRITA_JACZIBETH.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-Jaczibeth/files/9605418/MAPAMENTAL_COMUNICACION.ORALYESCRITA_JACZIBETH.pdf)

**Comment by Jaczibeth** [comment]
MI TRABAJO PROPORCIONE DOS ARCHIVOS 
UNO EN PNG POR SI NO SE VE POR QUE LUEGO DISMINUYE LA CALIDAD AL CONVERTIRLO Y ESO LO ESTOY PRESENTANDO MISMO TRABAJO PERO EN ARCHIVO PDF

**Comment by 11042002** [comment]
Tu calificación es de: 19%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
